[general]
static=yes
writeprotect=no

[financial-context]
exten => _XXXX,1,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

; Nueva regla de prueba con música de espera integrada
exten => 600,1,Answer()
 same => n,Playback(hello-world)    ; Te dirá "Hello World" en inglés
 same => n,Wait(1)
 same => n,Echo()                   ; Luego entra al eco habitual
 same => n,Hangup()
