[modules]
autoload=yes

; Precargas críticas para inicializar la base de datos de recursos (Sorcery)
preload => res_pjproject.so
preload => res_sorcery_config.so
preload => res_sorcery_memory.so
preload => res_sorcery_astdb.so

; Carga obligatoria del canal moderno de telefonía
load => res_pjsip.so
load => res_pjsip_session.so
load => chan_pjsip.so
load => pbx_config.so

; Desactivar módulos obsoletos que causan colapsos
noload => chan_alsa.so
noload => chan_oss.so
noload => res_hep.so
noload => res_hep_pjsip.so
