[modules]
autoload=yes

; Precargas obligatorias para romper la falta de dependencias de Sorcery
preload => res_pjproject.so
preload => res_sorcery_config.so
preload => res_sorcery_memory.so
preload => res_sorcery_astdb.so

; Carga explícita de los módulos core de telefonía requeridos
load => res_pjsip.so
load => res_pjsip_session.so
load => chan_pjsip.so
load => pbx_config.so

; Módulos que debes ignorar para evitar el crash del contenedor
noload => chan_alsa.so
noload => chan_oss.so
noload => res_hep.so
noload => res_hep_pjsip.so
